export const ADD_EVENT_RESULT = 'ADD_EVENT_RESULT';
export const DELETE_EVENT_RESULT = 'DELETE_EVENT_RESULT';

export const UPDATE_EVENT_ENTITIES = 'UPDATE_EVENT_ENTITIES';
export const DELETE_EVENT_ENTITIES = 'DELETE_EVENT_ENTITIES';

export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';
export const FETCH_EVENTS_ABORT = 'FETCH_EVENTS_ABORT';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_FULFILLED = 'FETCH_EVENT_FULFILLED';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
export const FETCH_EVENT_ABORT = 'FETCH_EVENT_ABORT';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_FULFILLED = 'CREATE_EVENT_FULFILLED';
export const CREATE_EVENT_FAILURE = 'CREATE_EMVENT_FAILURE';
export const CREATE_EVENT_ABORT = 'CREATE_EVENT_ABORT';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_FULFILLED = 'UPDATE_EVENT_FULFILLED';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';
export const UPDATE_EVENT_ABORT = 'UPDATE_EVENT_ABORT';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_FULFILLED = 'DELETE_EVENT_FULFILLED';
export const DELETE_EVENT_FAILURE = 'DELETE_EMVENTS_FAILURE';
export const DELETE_EVENT_ABORT = 'DELETE_ABORT_EVENT';